host: localhost
task:
  name: Creamos un servidor
  ec2:
    region: sa-esast-1
    instance_type: t2.micro
    image: ami-090006f29ecb2d79a
    keypair: pablodh
    wait: yes
    wait_timeout: 500
    volumes:
      device_name: /dev/xvda
      volume_type: gp2
      volume_size: 8
      vpc_subnet_id: subnet-06703e55efa810732
      assign_public_ip: yes
